version: '3.9'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    user: "${UID}:${GID}"
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --allowed-hosts '*'
    volumes:
      - mlflow_data:/mlflow
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  fraud_api:
    build: .
    container_name: fraud-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - PYTHONUNBUFFERED=1
    depends_on:
      - mlflow
      
volumes:
  mlflow_data: